// Code generated by protoc-gen-go.
// source: entry.proto
// DO NOT EDIT!

/*
Package entry is a generated protocol buffer package.

It is generated from these files:
	entry.proto

It has these top-level messages:
	Entry
*/
package entry

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// protoc --go_out=. entry.proto
type Entry struct {
	Timestamp        *int64 `protobuf:"fixed64,1,req,name=timestamp" json:"timestamp,omitempty"`
	Payload          []byte `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}

func (m *Entry) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Entry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
}
