// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ClientRequest
	ClientWriteRequest
	ClientReplayRequest
	ServerResponse
	ServerReplayResponse
	LogEntry
*/
package api

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ClientRequest_Type int32

const (
	ClientRequest_WriteRequest  ClientRequest_Type = 1
	ClientRequest_ReplayRequest ClientRequest_Type = 2
)

var ClientRequest_Type_name = map[int32]string{
	1: "WriteRequest",
	2: "ReplayRequest",
}
var ClientRequest_Type_value = map[string]int32{
	"WriteRequest":  1,
	"ReplayRequest": 2,
}

func (x ClientRequest_Type) Enum() *ClientRequest_Type {
	p := new(ClientRequest_Type)
	*p = x
	return p
}
func (x ClientRequest_Type) String() string {
	return proto.EnumName(ClientRequest_Type_name, int32(x))
}
func (x *ClientRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientRequest_Type_value, data, "ClientRequest_Type")
	if err != nil {
		return err
	}
	*x = ClientRequest_Type(value)
	return nil
}

type ServerResponse_Type int32

const (
	ServerResponse_ReplayResponse ServerResponse_Type = 1
)

var ServerResponse_Type_name = map[int32]string{
	1: "ReplayResponse",
}
var ServerResponse_Type_value = map[string]int32{
	"ReplayResponse": 1,
}

func (x ServerResponse_Type) Enum() *ServerResponse_Type {
	p := new(ServerResponse_Type)
	*p = x
	return p
}
func (x ServerResponse_Type) String() string {
	return proto.EnumName(ServerResponse_Type_name, int32(x))
}
func (x *ServerResponse_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerResponse_Type_value, data, "ServerResponse_Type")
	if err != nil {
		return err
	}
	*x = ServerResponse_Type(value)
	return nil
}

type ServerResponse_Status int32

const (
	ServerResponse_OK    ServerResponse_Status = 1
	ServerResponse_Error ServerResponse_Status = 2
)

var ServerResponse_Status_name = map[int32]string{
	1: "OK",
	2: "Error",
}
var ServerResponse_Status_value = map[string]int32{
	"OK":    1,
	"Error": 2,
}

func (x ServerResponse_Status) Enum() *ServerResponse_Status {
	p := new(ServerResponse_Status)
	*p = x
	return p
}
func (x ServerResponse_Status) String() string {
	return proto.EnumName(ServerResponse_Status_name, int32(x))
}
func (x *ServerResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerResponse_Status_value, data, "ServerResponse_Status")
	if err != nil {
		return err
	}
	*x = ServerResponse_Status(value)
	return nil
}

// ClientRequest is a request to the server which should either be a
// ClientWriteRequest or a ClientReplayResuest
type ClientRequest struct {
	Type             *ClientRequest_Type       `protobuf:"varint,1,req,name=type,enum=ClientRequest_Type" json:"type,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}

var extRange_ClientRequest = []proto.ExtensionRange{
	{100, 536870911},
}

func (*ClientRequest) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ClientRequest
}
func (m *ClientRequest) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *ClientRequest) GetType() ClientRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ClientRequest_WriteRequest
}

// ClientWriteRequest is a message to the server to persist
// this message payload
type ClientWriteRequest struct {
	Payload          []byte `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClientWriteRequest) Reset()         { *m = ClientWriteRequest{} }
func (m *ClientWriteRequest) String() string { return proto.CompactTextString(m) }
func (*ClientWriteRequest) ProtoMessage()    {}

func (m *ClientWriteRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

var E_ClientWriteRequest_Request = &proto.ExtensionDesc{
	ExtendedType:  (*ClientRequest)(nil),
	ExtensionType: (*ClientWriteRequest)(nil),
	Field:         100,
	Name:          "ClientWriteRequest.request",
	Tag:           "bytes,100,opt,name=request",
}

// ClientReplayRequest is a message to the server to replay the log
type ClientReplayRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClientReplayRequest) Reset()         { *m = ClientReplayRequest{} }
func (m *ClientReplayRequest) String() string { return proto.CompactTextString(m) }
func (*ClientReplayRequest) ProtoMessage()    {}

var E_ClientReplayRequest_Request = &proto.ExtensionDesc{
	ExtendedType:  (*ClientRequest)(nil),
	ExtensionType: (*ClientReplayRequest)(nil),
	Field:         101,
	Name:          "ClientReplayRequest.request",
	Tag:           "bytes,101,opt,name=request",
}

// ServerReplayResponse is a servers response to a message from
// the client
type ServerResponse struct {
	Type             *ServerResponse_Type      `protobuf:"varint,1,req,name=type,enum=ServerResponse_Type" json:"type,omitempty"`
	Status           *ServerResponse_Status    `protobuf:"varint,2,req,name=status,enum=ServerResponse_Status,def=1" json:"status,omitempty"`
	Error            *string                   `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}

var extRange_ServerResponse = []proto.ExtensionRange{
	{100, 536870911},
}

func (*ServerResponse) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ServerResponse
}
func (m *ServerResponse) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_ServerResponse_Status ServerResponse_Status = ServerResponse_OK

func (m *ServerResponse) GetType() ServerResponse_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ServerResponse_ReplayResponse
}

func (m *ServerResponse) GetStatus() ServerResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_ServerResponse_Status
}

func (m *ServerResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

// ServerReplayResponse is a message from the server with a
// number of replayed log entries
type ServerReplayResponse struct {
	Entry            *LogEntry `protobuf:"bytes,1,req,name=entry" json:"entry,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ServerReplayResponse) Reset()         { *m = ServerReplayResponse{} }
func (m *ServerReplayResponse) String() string { return proto.CompactTextString(m) }
func (*ServerReplayResponse) ProtoMessage()    {}

func (m *ServerReplayResponse) GetEntry() *LogEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

var E_ServerReplayResponse_Response = &proto.ExtensionDesc{
	ExtendedType:  (*ServerResponse)(nil),
	ExtensionType: (*ServerReplayResponse)(nil),
	Field:         100,
	Name:          "ServerReplayResponse.response",
	Tag:           "bytes,100,opt,name=response",
}

// LogEntry is a single entry in the log
type LogEntry struct {
	Timestamp        *int64 `protobuf:"fixed64,1,req,name=timestamp" json:"timestamp,omitempty"`
	Payload          []byte `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}

func (m *LogEntry) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *LogEntry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("ClientRequest_Type", ClientRequest_Type_name, ClientRequest_Type_value)
	proto.RegisterEnum("ServerResponse_Type", ServerResponse_Type_name, ServerResponse_Type_value)
	proto.RegisterEnum("ServerResponse_Status", ServerResponse_Status_name, ServerResponse_Status_value)
	proto.RegisterExtension(E_ClientWriteRequest_Request)
	proto.RegisterExtension(E_ClientReplayRequest_Request)
	proto.RegisterExtension(E_ServerReplayResponse_Response)
}
